
params.reads="R10_q9l500.fastq.gz"




log.info """\
         LR_MAPPING - N F   P I P E L I N E
         ===================================
         reads           : ${params.reads}
         """
         .stripIndent()

/*
We will be using the FASTQ data for Escherichia coli K12MG1655 sequenced on the latest
R10.4 flowcell on ONT MinION platform. The raw fast5 data can be downloaded from ENA
under the study PRJEB36648. This is a test dataset generated by Dr. Rasmus H. Kirkegaard
from Albersten lab (https://albertsenlab.org/).
We have already generated the trimmed data using NanoFilt (Average quality:9 and
Length:500) and the file is made available. We have also got E.coli K12 MG1655 reference
genome and ODB database for gammaproteobacteria and other polishing models, which will
be used at a later stage.
*/


/*
4.3 Generate de novo genome assembly
Flye is one of the most widely used tools for assembling genomes from long noisy reads.
Shasta is a relatively new assembler but is extremely fast in generating assemblies. Both of
them are designed for a wide range of datasets from small bacteria to large mammals. It is
always a good idea to generate the assemblies with more than one assembler, as each one of
them might be better/worse in different aspects.

*/


Channel
  .fromPath(params.reads)
  .set{reads}


process flye {
  cpus 8

  input:
  path(reads)

  output:
  path("assembly*") into assembly_ch

  script:
  """
  flye \
  --nano-raw  ${reads}\
  -g 5M \
  -o flye \
  -t ${task.cpus}
  """

}

/*
The Shasta assembler provides a lot of output files that allows exploring details of many data
structures used during assembly. The assembled contig/scaffold sequences are provided in
the file “Assembly.fasta”.
*/

Channel
  .fromPath(params.reads)
  .set{reads}

process shasta {
  cpus 8

  input:
  path(reads)

  script:
  sampleID=reads.simpleName
  """

  gunzip -c ${reads} > ${sampleID}.fastq

  shasta \
  --input ${sampleID}.fastq \
  --assemblyDirectory shasta \
  --threads  ${task.cpus}  \
  --config shasta.conf
  """
}


/*
4.4 Assessment of assemblies
4.4.1 Using QUAST
QUAST is a quality assessment tool for evaluating and comparing genome assemblies.
QUAST can evaluate assemblies both with a reference genome, as well as without a reference.
*/

/*
process quast {
cpus 8
  script:
  """
  quast \
  -o quast_flye_shasta \
  -t ${task.cpus} \
  --labels flye,shasta
  flye/assembly.fasta shasta/Assembly.fasta \
  -r reference/K12_MG1655.fna
  """

}

*/

/*
BUSCO:
BUSCO provides a rich source of data to assess the quality and completeness of
genome assemblies, gene annotations, and transcriptomes by comparing them to
OrthoDB’s sets of Benchmarking Universal Single-Copy Orthologs. We will run this on
both assemblies generated so far.
*/

/*
prcoess busco {

  input:


  script:
  """
  for i in flye shasta;
  do
  (echo "busco -i $i.fasta -o ${i}_busco -m
  genome -l gammaproteobacteria_odb10/ -f -c 8");
  done | bash
  """
}*/
